### ISSUE TITLE
Playd a game with no hits and 58 Experience, should that be possible?

### ISSUE THREAD

**Issue by gcarreno** [cyberfilth/Axes-Armour-Ale#10]
Hi Chris,

Like the title says, I've played a game where I battle 3 or four `h` and some more `r` and never got a hit.

Isn't the hit and miss a `RND` factor? Or is that off for testing purposes under development?

Cheers,
Gus

**Comment by cyberfilth** [comment]
Hi, that's under development at the moment.
Until now, the player has been a separate type of entity to the enemy characters. I'm now refactoring all of the player and entity code so that the player is treated as just another entity. Also, NPC's will be able to have the same status effects as the player going forward.

The combat and map functions haven't been fully rewritten yet so after a few more commits the Random Number Generator should be a little fairer in combat.

Normally I'd keep these refactorings in a development branch but since all of the code base is in alpha I've been working in master.

After this I'll probably start using a separate feature branch

**Comment by cyberfilth** [comment]
[Commit 96](https://github.com/cyberfilth/Axes-Armour-Ale/commit/da4efedf288021c3bb93dd355e64a8b826bf0d5a) puts back the combat function in the player code.
NPC combat still needs tweaking though
