### ISSUE TITLE
What happened to the `.lpi`?

### ISSUE THREAD

**Issue by gcarreno** [cyberfilth/Axes-Armour-Ale#46]
Hey Chris (@cyberfilth),

At some point in the past I remember compiling the app with a simple call to `lazbuild`.

There is now an absence of an `.lpi` file in order to use `lazbuild`.

With an `.lpi` you can have the build modes in it. One, two, as many as you wish...
A simple Debug/Release compilation is a command line switch away: `--bm=Release` or `--bm=Debug`.
I could list a ton more advantages of the fact that the Free Pascal devs decided to have an `.lpi` but it doesn't matter.

I was actually gonna contribute some GitHub actions workflow in order to have compiled and archived binaries for Windows, Linux and macOS created upon a release with automated release notes and all.

I think this is still doable, since you have the scripts, but it will be a bit more involved than just calling `lazbuild Axes.lpi` ☹️

But I still wonder: Why the sudden decision to abandone the `.lpi` ?

Cheers,
Gus

**Comment by cyberfilth** [comment]
Hiya Gus,

For a while, one of the Lazarus builds that I was using lost the ability to run a console application from an attached terminal, meaning that I couldn't use the integrated debugger.

I found that the textmode Free Pascal IDE worked just fine though, and I could use it to set break / watch points easily, and it included release / debug modes. But it doesn't recognise Lazarus project files so I started using plain .pas files.
After a while, I eventually bit the bullet and started using Vim for development (just because the autocomplete in the FP IDE sucks), and gdb for debugging, so the .lpi file stopped being updated.

The last version of Lazarus that I played with, the option to run a command line program from an attached terminal is working again. But now I'm a lot more comfortable coding in Vim for terminal programs, and don't see myself switching back.

Sorry if this is another hoop to jump through, I can add a compilation script for OSX from an old one that I can update.
